import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import { ProductProvider } from "@/context/ProductContext";
import { SearchProvider } from "@/context/SearchContext";
import { Suspense } from "react";
import LoadingPage from "./loading";
import Footer from "@/components/common/Footer";
import { CartProvider } from "@/context/CartContext";
import { headers } from "next/headers";
import { UserProvider } from "@/context/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <UserProvider>
          <CartProvider>
            <SearchProvider>
              <ProductProvider>
                <Navbar />
                <main className="flex-grow">
                  <Suspense fallback={<LoadingPage />}>{children}</Suspense>
                </main>
                <Footer />
              </ProductProvider>
            </SearchProvider>
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
