import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // Adjust the path if needed
import SideBar from "@/components/user/admin/Sidebar";
import { Suspense } from "react";
import LoadingPage from "../loading";
import { ProductProvider } from "@/context/ProductContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${inter.className} flex min-h-screen`}>
      <ProductProvider>
        <div className="flex flex-1 min-h-screen">
          <div className="w-1/6 bg-side-sidebar-bg lg:sticky lg:top-0 lg:h-screen">
            <SideBar />
          </div>
          <main className="flex-grow overflow-y-auto">
            <Suspense fallback={<LoadingPage />}>{children}</Suspense>
          </main>
        </div>
      </ProductProvider>
    </div>
  );
}
